on:
  push:
    tags:
      - 'v*'

name: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install toolchain and build
        run: |
          mkdir $GITHUB_WORKSPACE/toolchain
          cd $GITHUB_WORKSPACE/toolchain
          wget https://releases.linaro.org/components/toolchain/binaries/5.1-2015.08/arm-linux-gnueabi/gcc-linaro-5.1-2015.08-x86_64_arm-linux-gnueabi.tar.xz
          tar xf gcc-linaro-5.1-2015.08-x86_64_arm-linux-gnueabi.tar.xz
          echo "$GITHUB_WORKSPACE/toolchain/gcc-linaro-5.1-2015.08-x86_64_arm-linux-gnueabi/bin" >> $GITHUB_PATH
          cd ..
          ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: inject.o
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
